import: a16bitsysop/travis-build-configs:docker-apt.yml

env:
  - IMAGE_NAME=a16bitsysop/dccifd APK=dcc

before_script:
  - VER=$(version.py -a $APK)
  - VER=$VER"-alpine"$(version.py -b)
  - TAG="-t $IMAGE_NAME:$VER"
  - |
      MY_VER="$(version.py -d $IMAGE_NAME)"
      echo "Alpine Version $VER"
      echo "Docker Version $MY_VER"
      if [ -z $NOW ] && [ -n "$MY_VER" ] && [ "$MY_VER" = "$VER" ]; then travis_terminate 0; fi

script:
  - if [ -z "$NOW" ] || [ "$NOW" = "later" ]; then for i in {1..15}; do sleep 1m; echo "waiting $i mins"; done; fi
  - docker-build.sh "$TAG" "$ALP_VER" "$APK_VER"
  - curl -X POST "https://hooks.microbadger.com/images/$IMAGE_NAME/$WEBHOOK"
